## Colors configuration
[colors.primary]
background = "#000000"
foreground = "#ffffff"

[colors.normal]
black   = "#000000"
red     = "#ffffff"
green   = "#ffffff"
yellow  = "#ffffff"
blue    = "#ffffff"
magenta = "#ffffff"
cyan    = "#ffffff"
white   = "#ffffff"

[colors.bright]
black   = "#000000"
red     = "#ffffff"
green   = "#ffffff"
yellow  = "#ffffff"
blue    = "#ffffff"
magenta = "#ffffff"
cyan    = "#ffffff"
white   = "#ffffff"
